version: '3.8'
services:
  mysql:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: oauth2-oidc
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    ports:
      - "3306:3306"

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      - DSN=mysql://root:secret@tcp(mysql:3306)/oauth2-oidc
    command: migrate sql -e --yes
    depends_on:
      mysql:
        condition: service_healthy

  hydra:
    image: oryd/hydra:v2.3.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    ports:
      - "4444:4444"  # Public API
      - "4445:4445"  # Admin API
    environment:
      - DSN=mysql://root:secret@tcp(mysql:3306)/oauth2-oidc
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_ENABLED=true
      - URLS_SELF_ISSUER=http://localhost:4444/
      - URLS_CONSENT=http://localhost:3000/consent
      - URLS_LOGIN=http://localhost:3000/login
      - LOG_LEVEL=debug
      - SECRETS_SYSTEM=somesupersecret123456
      - SERVE_PUBLIC_TLS_ENABLED=false
      - SERVE_ADMIN_TLS_ENABLED=false
      - DEV=true
    command: serve all --dev
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully

  mysql_exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: mysql-mysqld_exporter-1
    restart: unless-stopped
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy

networks:
  default:
    external: true
    name: hydra_benchmark_network

volumes:
  mysql_data:
