global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-postgres_exporter-1:9187']
    metrics_path: /metrics

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-mysqld_exporter-1:9104']
    metrics_path: /metrics

  - job_name: 'hydra-postgres'
    static_configs:
      - targets: ['postgres-hydra-1:4445']
    metrics_path: /admin/metrics/prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'hydra-postgres'

  - job_name: 'hydra-mysql'
    static_configs:
      - targets: ['mysql-hydra-1:4445']
    metrics_path: /admin/metrics/prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'hydra-mysql'
